export const homeData = () => {
  return `*[_type == "home"]{
    name,
    title,
     images[]{
      asset->{
        url
      }
    },
    cars[]{
      carname,
      logoImage {
        asset->{
          url
        }
      },
      locations[]{
       locationName,
        chargingStation[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        maintenanceCenter[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        sparePartsStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        accessoriesStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        chargerStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        carShowroom[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time
          }
        },
        services[]{
          components[]{
            winches[]{
              StoreFullName,
              phoneNumber,
              location
            },
            chargeonroad[]{
              StoreFullName,
              phoneNumber,
              location
            },
            dryclean[]{
              StoreFullName,
              phoneNumber,
              location
            }
          }
        }
      }
    }
  }`;
};
