export const homeData = () => {
  return `*[_type == "home"]{
    name,
    title,
    images[]{
      asset->{
        url
      }
    },
    cars[]{
      carname,
      logoImage {
        asset->{
          url
        }
      },
      locations[]{
        locationName,
        chargingStation[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        maintenanceCenter[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        sparePartsStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        accessoriesStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        chargerStore[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        carShowroom[]{
          StoreName,
          storeInfo[]{
            StoreFullName,
            price,
            phoneNumber,
            location,
            time,
            locationFullName
          }
        },
        services[]{
          components[]{
            winches[]{
              SName,
              details[]{
                ServiceStoreFullName,
                ServicePhoneNumber,
                ServiceLocation
              }
            },
            chargeonroad[]{
              SName,
              details[]{
                ServiceStoreFullName,
                ServicePhoneNumber,
                ServiceLocation
              }
            },
            dryclean[]{
              SName,
              details[]{
                ServiceStoreFullName,
                ServicePhoneNumber,
                ServiceLocation
              }
            }
          }
        }
      }
    }
  }`;
};
